### PR TITLE
Make method signature compatible again

### LINKED ISSUE #149: validateFields() is not compatible after updating to Nova 3.21.0
ErrorException: Declaration of Epartment\NovaDependencyContainer\HasDependencies::validateFields() should be compatible with Laravel\Nova\Actions\Action::validateFields(Laravel\Nova\Http\Requests\ActionRequest $request).

Using Laravel Nova 3.21.0 and Nova Field Dependency Container 1.2.11. Confirmed that this error does not occur with Nova 3.20.0.

It looks like Nova's `validateFields()` now takes an argument `$request` that NovaDependencyContainer's `validateFields()` is not accepting.
Stack trace is attached. Please let me know if there is anything else I can do to help diagnose.

Screen Shot 2021-02-02 at 4 45 39 PM

### PR DESCRIPTION
**Pull request by dododedodonl**
This PR makes the method signature of `validateFields` compatible again with the definition in nova 3.21.0.

Have not tested functionality changes, but my implementations are still working.
Have not tested against older versions of nova, but this way of overriding the method should be compatible.

Resolves #149

### CODE REVIEW

File: src/HasDependencies.php [hunk 1]
```diff
@@ -139,9 +140,10 @@ protected function applyRulesForChildFields($childField)
     /**
      * Validate action fields
      * Overridden using ActionController & ActionRequest by modifying routes
+     * @param  \Laravel\Nova\Http\Requests\ActionRequest  $request
      * @return void
      */
-    public function validateFields() {
+    public function validateFields(ActionRequest $request = null) {
```
Comment (ragingdave) [inline src/HasDependencies.php:146]: Why the fallback to null here? I tested a few of my usages of resources and a new action using the same code just without the null default and I didn't get an error.

Comment (dododedodonl) [reply src/HasDependencies.php:146]: In nova versions <3.21.0, this method might be called without any arguments, so defaulting to null would solve this

Comment (ragingdave) [reply src/HasDependencies.php:146]: hmm good point there. Good safety net then.

**Comment by ragingdave** [comment]
Thanks for the addition!
